#include "dkl.h"
#ifndef MKL_COMPAT_H
#define MKL_COMPAT_H

#define MKL_INTERFACE_ILP64 1
#define MKL_THREADING_INTEL 0
#define MKL_PEAK_MEM_ENABLE 1
#define MKL_PEAK_MEM 2

void vdExp(const DKL_INT, const double *, double *);
void cblas_dscal(const DKL_INT, const double a, double *x, const DKL_INT incx);
void mkl_ddnscsr(const DKL_INT *job, const DKL_INT *m, const DKL_INT *n,
                 double *adns, const DKL_INT *lda, double *acsr, DKL_INT *ja,
                 DKL_INT *ia, DKL_INT *info);
void pardiso_64(void *pt, DKL_INT *maxfct, DKL_INT *mnum, DKL_INT *mtype,
                DKL_INT *phase, DKL_INT *n, void *a, DKL_INT *ia, DKL_INT *ja,
                DKL_INT *perm, DKL_INT *nrhs, DKL_INT *iparm, DKL_INT *msglvl,
                void *b, void *x, DKL_INT *error);
DKL_INT MKL_Peak_Mem_Usage(int mode);

// PARDISO-specific parameters

// Matrix types
#define MKL_PARDISO_MATRIX_TYPE_REAL_STRUCT_SYMMETRIC 1
#define MKL_PARDISO_MATRIX_TYPE_REAL_SYMMETRIC_POS_DEF 2
#define MKL_PARDISO_MATRIX_TYPE_REAL_SYMMETRIC_INDEF -2
#define MKL_PARDISO_MATRIX_TYPE_COMPLEX_STRUCT_SYMMETRIC 3
#define MKL_PARDISO_MATRIX_TYPE_COMPLEX_HERMITIAN_POS_DEF 4
#define MKL_PARDISO_MATRIX_TYPE_COMPLEX_HERMITIAN_INDEX -4
#define MKL_PARDISO_MATRIX_TYPE_COMPLEX_SYMMETRIC 6
#define MKL_PARDISO_MATRIX_TYPE_REAL_UNSYMMETRIC 11
#define MKL_PARDISO_MATRIX_TYPE_COMPLEX_UNSYMMETRIC 13

// Solver phases
#define MKL_PARDISO_SOLVER_PHASE_ANALYSIS 11
#define MKL_PARDISO_SOLVER_PHASE_ANALYSIS_NUMERICAL_FACTORIZATION 12
#define MKL_PARDISO_SOLVER_PHASE_ANALYSIS_NUMERICAL_FACTORIZATION_SOLVE 13
#define MKL_PARDISO_SOLVER_PHASE_NUMERICAL_FACTORIZATION 22
#define MKL_PARDISO_SOLVER_PHASE_NUMERICAL_FACTORIZATION_SOLVE 23
#define MKL_PARDISO_SOLVER_PHASE_SOLVE_ITERATIVE_REFINEMENT 33
#define MKL_PARDISO_SOLVER_PHASE_SOLVE_FORWARD_SUBSTITUTION 331
#define MKL_PARDISO_SOLVER_PHASE_SOLVE_DIAGONAL_SUBSTITUTION 332
#define MKL_PARDISO_SOLVER_PHASE_SOLVE_BACKWARD_SUBSTITUTION 333
#define MKL_PARDISO_SOLVER_PHASE_RELEASE_MEMORY_MNUM 0
#define MKL_PARDISO_SOLVER_PHASE_RELEASE_MEMORY_ALL -1

#endif /* MKL_COMPAT_H */
